---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pdf-service
  labels:
    app: pdf-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pdf-service
    spec:
      containers:
      - name: pdf-service
        image: pdf-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 9080
---
apiVersion: v1
kind: Service
metadata:
  name: pdf-service
  labels:
    app: pdf-service
spec:
  type: NodePort
  ports:
  # the port that this service should serve on
  - port: 9080
    targetPort: 9080
    nodePort: 31180
  selector:
    app: pdf-service