apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: kafka
  name: kafka
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - env:
# Deprecated      
#        - name: MY_POD_NAME
#          valueFrom:
#            fieldRef:
#              fieldPath: metadata.name      
#        - name: KAFKA_ADVERTISED_HOST_NAME
#          value: "$(MY_POD_NAME)"
#        - name: KAFKA_ADVERTISED_PORT
#          value: "9092"
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: MY_MINIKUBE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP          
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "$(MY_MINIKUBE_IP):30181"
        - name: KAFKA_CREATE_TOPICS
          value: "demo:1:1"
        - name: KAFKA_LISTENERS
          value: "PLAINTEXT://:9092"  
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: KAFKA_ADVERTISED_LISTENERS        
          value: "PLAINTEXT://$(MY_POD_IP):9092" 
        image: wurstmeister/kafka
        imagePullPolicy: Always
        name: kafka
        ports:
        - containerPort: 9092